[build]
  publish = "public"
  command = "echo SITE_RECAPTCHA_KEY=6LcpNGwUAAAAAPwK9rgBokrTvGUvDVur5faRqdEc >> .env.production && npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
  SITE_RECAPTCHA_KEY = "6LcpNGwUAAAAAPwK9rgBokrTvGUvDVur5faRqdEc"
  SITE_RECAPTCHA_SECRET = "6LcpNGwUAAAAAKVtJO-ZBk1fRB_ilEAaPiPcuAw0"
