[build]
  publish = "public"
  command = "echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> env.production && npm run build"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"


